### ISSUE TITLE
Cancelling a message doesn't work

### ISSUE THREAD

**Issue by zachblume** [upstash/issues#83] opened 2023-11-26 17:24 UTC
- Created a message
- It failed
- I hit cancel
- It said: All good! Messaged cancelled
- It's still there
- I refresh, no change
- messageId: msg_26hZCxZCuWyyTWPmSVBrNB882AKfGDBDJnnhjJRSxcHDYZ86AUeNLRzKvYSRzxG

**Comment by zachblume** [comment] 2023-11-26 17:25
Same message also says "The message was already delivered or moved to the DLQ, headers and body might not be visible anymore" but that's not true -- it wasnt delivering, it is retyring, and i looked at my DLQ and its empty.

**Comment by Gbuomprisco** [comment] 2023-11-27 00:46
Same here. The API also doesn't seem to be able to find it.

**Comment by sancar** [comment] 2023-11-27 09:17
@zachblume The cancel gets the request and saves it until the next attempt. Right before the next attempt, the message will be cancelled. Meaning it will be removed and you will no longer access the message via `/v2/messages/{messageid}` 
It will not be in DLQ as well as it is cancelled. 

This is the current behavour but I also realize that it is not that straight-forward. And the message on the UI is not correct in case of `cancel` .  In the logs, you should see `CANCEL_REQUESTED` though to indicate that the request is successful. And before the next attempt it will log `CANCELLED` . Can you share all the logs of the message for us to understand the issue more ?


@Gbuomprisco Your one might be different. Which API are you referring to  ? This one  `/v2/messages/{messageid}` ? 
Can you also share the message id and the logs of the message ?

**Comment by Gbuomprisco** [comment] 2023-11-27 14:30
Hi @sancar

1. `CANCEL_REQUESTED` does not appear after I cancel a message in the logs
2. Yes - I use that endpoint with the IDs referred to in the logs, such as: msg_26hZCxZCuWyyTWPmSVBrNC1RADRpoFbb4iD3mK98t8WP4zVGTi6FcWj8Z5ewDN8

**Comment by sancar** [comment] 2023-11-28 08:19
Hi @Gbuomprisco , we can reproduce the issue. There seems to be a bug. We are investigating the root cause. 

The cancel seems to be failing time to time not always. And as you said, the message can not be found after this happens. 

We will update the here when the issue is resolved.

**Comment by sancar** [comment] 2023-11-28 09:32
We have identified the root cause. It is a new regression caused by the release next week. We will do a new release this week with the fix and update here.

**Comment by sancar** [comment] 2023-11-29 15:13
@Gbuomprisco  @zachblume  The fix is released. Closing the issue. Please try and reopen the issue if you see any problem.

**Closed by sancar** 2023-11-29 15:13 UTC
