### ISSUE TITLE
Operation Failed: Only create 1 free database

### ISSUE THREAD

**Issue by andre347** [upstash/issues#10] opened 2021-07-12 17:56 UTC
When trying to create my 1 free database I get this error message. If I click on databases on the left hand panel I don't see any databases created so something must be going wrong. Tried on Firefox, Safari and Chrome. Also created two seperated accounts (Github and Google) - same problem. In the network tab I see a 400 response coming backing saying the same as the error toast below.

<img width="432" alt="Screenshot 2021-07-12 at 19 53 41@2x" src="https://user-images.githubusercontent.com/22317522/125333919-12a83d00-e34b-11eb-8804-3bc251d22079.png">

**Comment by enesakar** [comment] 2021-07-12 18:26
I manually fixed your quota. You should be fine. But we are investigating how this happened.

**Comment by andre347** [comment] 2021-07-12 18:41
> I manually fixed your quota. You should be fine. But we are investigating how this happened.

Thanks! Also for the quick reply.

**Comment by enesakar** [comment] 2021-07-13 07:01
We found the root cause and fixed it. Closing the issue.

**Closed by enesakar** 2021-07-13 07:01 UTC
