### ISSUE TITLE
the UI

### ISSUE THREAD

**Issue by fkadeal** [upstash/issues#89] opened 2024-02-01 10:30 UTC
![image](https://github.com/upstash/issues/assets/44930374/62806c6a-8983-4204-83b0-dc9a9ae87c55)

**Comment by sancar** [comment] 2024-02-01 10:35
Hi @fkadeal Thanks for the report. We are looking into it.

**Comment by sancar** [comment] 2024-02-01 13:38
The problem is resolved. Closing the issue.

**Closed by sancar** 2024-02-01 13:38 UTC
